const express = require('express');
const path = require("path");
const nodemailer = require('nodemailer');
const fs = require('fs');
var easyinvoice = require('easyinvoice');

const router = express.Router();

//Ruta za dashboard
router.get('/', (req, res) => {
  let moduleTemp = {firstName: req.session.firstName, adminUser: req.session.isAdmin, freeSpaces: 1, occupiedSpaces: 1, totalSpaces: 1, totalProfit:1, usageByZone: [["Zona1", 1000, 2313, 1]]};
  res.render('dashboard', moduleTemp);
});

//Ruta za logout
router.post('/logout', (req, res) => { 
  //Dodaj logout
  console.log("Logout")
});

//Ruta za logout
router.get('/downloadDailyReport', (req, res) => {
  console.log(234234)
  // Sample data for the report (you can replace this with your actual data)
  const randomData = {
    water: [/* Water consumption data */],
    energy: [/* Energy consumption data */],
    gas: [/* Gas consumption data */],
    profit: [/* Profit data */],
  };

  const invoiceData = {
    document: {
      title: '24-Hour Report',
      number: '001',
      footer: 'Generated by Your App',
    },
    client: {
      company: 'Client Company',
      address: '123 Client St, City',
      email: 'client@email.com',
    },
    items: [
      // Add items for water, energy, gas, and profit here
    ],
  };

  // Generate the PDF invoice
  easyinvoice.createInvoice(invoiceData, function (result) {
    const pdfBuffer = Buffer.from(result.pdf, 'base64');

    // Save the PDF to a file (optional)
    fs.writeFileSync('data/24-hour-report.pdf', pdfBuffer);

    // Send the PDF as a response to the client
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="24-hour-report.pdf"');
    res.send(pdfBuffer);
    console.log(234234)
  });
});


module.exports = router;